#ifndef _RES_REF_
#define _RES_REF_


//uart
#define UART_RXTX_BT UART0_RX_PA15_TX_PA14
#define UART_BT HW_UART0
//Steering gear
#define FTM_PWM_STEERING FTM1_CH1_PA09
#define FTM_CHL_STEERING HW_FTM_CH1
#define FTM_STEERING HW_FTM1
//SPEED ENCODER
#define DMA_CHL_SPEED HW_DMA_CH0
#define DMA_REQ_SPEED PORTC_DMAREQ
#define PORT_SPEED HW_GPIOC
#define GPIO_PIN_SPEED 5
//cam

//linear CCD1
#define ADC_HW HW_ADC1
#define PIT_CHL_CCD_CLK HW_PIT_CH0
#define GPIO_PIN_CCD_SI 2
#define GPIO_PIN_CCD_CLK 0
#define GPIO_PIN_CCD_HW HW_GPIOB
//linear CCD2

//MOTOR
#define FTM_PWM_MOTOR_RIGHT FTM0_CH0_PC01
#define FTM_MOTOR_RIGHT HW_FTM0
#define FTM_CHL_MOTOR_RIGHT HW_FTM_CH0

#define FTM_PWM_MOTOR_LEFT FTM0_CH3_PC04
#define FTM_MOTOR_LEFT HW_FTM0
#define FTM_CHL_MOTOR_LEFT HW_FTM_CH3

//PIT
#define PIT_CHL_CLK HW_PIT_CH1 

#endif